import { GoogleGenAI, Modality, Part } from "@google/genai";
import { Product } from '../types';

const apiKey = process.env.API_KEY;

export const isApiKeySet = !!apiKey;

let ai: GoogleGenAI | null = null;
if (isApiKeySet) {
    ai = new GoogleGenAI({ apiKey });
} else {
    console.error("VITE_GEMINI_API_KEY is not set. The app will have limited functionality.");
}


// Helper function to fetch an image from a URL and convert it to a base64 string
const urlToBase64 = async (url: string): Promise<{ data: string, mimeType: string }> => {
    const response = await fetch(url);
    if (!response.ok) {
        throw new Error(`Failed to fetch image from ${url}: ${response.statusText}`);
    }
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
            if (reader.error) {
                return reject(reader.error);
            }
            const base64Data = (reader.result as string).split(',')[1];
            resolve({ data: base64Data, mimeType: blob.type });
        };
        reader.onerror = (error) => reject(error);
        reader.readAsDataURL(blob);
    });
};

export const generateTryOnImage = async (
    personImageBase64: string,
    personImageMimeType: string,
    products: Product[]
): Promise<string> => {
    if (!ai) {
        throw new Error("Gemini API key is not configured. Please set it in your deployment environment variables.");
    }
    
    try {
        const personImagePart: Part = {
            inlineData: {
                data: personImageBase64,
                mimeType: personImageMimeType,
            },
        };

        const productPromises = products.map(product => urlToBase64(product.imageUrl));
        const productImages = await Promise.all(productPromises);

        const productImageParts: Part[] = productImages.map(image => ({
            inlineData: {
                data: image.data,
                mimeType: image.mimeType,
            },
        }));

        const productNames = products.map(p => `"${p.name}"`).join(', ');
        const textPart: Part = {
            text: `Take the clothing items from the following images and realistically place them on the person in the first image to create a complete outfit. The clothing items are: ${productNames}. The person should be wearing all the items, layered correctly (e.g., a shirt under a jacket). Maintain the original background and the person's pose.`,
        };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image-preview',
            contents: {
                parts: [
                    personImagePart,
                    ...productImageParts,
                    textPart,
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE, Modality.TEXT],
            },
        });
        
        if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    return part.inlineData.data;
                }
            }
        }

        throw new Error("No image was generated by the model.");

    } catch (error) {
        console.error("Error generating virtual try-on image:", error);
        throw new Error("Failed to generate virtual try-on image. Please try again.");
    }
};